#!/bin/bash

#Create the cluster with the above etcd key (no ssh keys)
cluster_id=`curl https://discovery.etcd.io/new` && echo $cluster_id
sed -i "s_discovery.*_discovery: ${cluster_id}_g" cloud-config.yaml

#Create the pmx-agent vm with a new etcd key & ssh keys
echo -e  'y\n'|ssh-keygen -q -t rsa -N '' -f id_rsa
ssh_key_pub="$(<id_rsa.pub)"
ssh_key_pri="$(cat id_rsa  | base64)"
sed -i "s_ssh-rsa.*_${ssh_key_pub}_g" cloud-config-agent.yaml


brightbox config client_add $APP_ID $SECRET_ID
server_group=`brightbox -s groups create -n "coreos" | grep -o grp.* | awk '{print $1}'`

firewall_policy_id=`brightbox firewall-policies create -n "coreos" $server_group | grep -o fwp.* |  awk '{print $1}'`
brightbox -s firewall-rules create --source any --protocol tcp --dport 22,7001,4001 $firewall_policy_id
brightbox -s firewall-rules create --destination any $firewall_policy_id

vm_size=${TYPE:-nano}
vm_name=${VM_NAME:-"coreos"}

coreos_vm_id=`brightbox servers create -i $NODE_COUNT --type $vm_size --name $vm_name --user-data-file cloud-config.yaml --server-groups $server_group img-2aptj | grep -o -m1 srv.* | awk '{print $1}'`
pmx_installer_id=`brightbox -s servers create -i 1 --type nano --name "pmxinstaller" --user-data-file cloud-config-agent.yaml --server-groups $server_group img-2aptj | grep -o -m1 srv.* | awk '{print $1}'`

private_ip=`brightbox -s servers show $coreos_vm_id | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
pmx_installer_ip=`brightbox -s cloudips create --name  "pmx_installer_ip" | grep -Eo cip-.* | awk '{print $1}'`

sleep 10
pmx_installer_public_ip=`brightbox cloudips map $pmx_installer_ip $pmx_installer_id  | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`

echo -e "\nFleet API IP: http://$private_ip:4001"
echo -e "\nPMX Installer IP: $pmx_installer_public_ip"
echo -e "\n\n\n$ssh_key_pri\n\n\n"


#Creating etcd keys
etcd_api=http://${ETCD_API}/v2/keys
curl  --data-urlencode -sL -X PUT $etcd_api/agent-pri-ssh-key -d "value=$ssh_key_pri"
curl -sL -X PUT $etcd_api/agent-fleet-api -d value=$private_ip
curl -sL -X PUT $etcd_api/agent-public-ip -d value=$pmx_installer_public_ip

until [ "1" == "0" ];
do
  sleep 20
done
